"""init schema

Revision ID: 246d6a30a544
Revises:
Create Date: 2026-06-14 18:59:26.243380

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "246d6a30a544"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subreddits",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subreddits")),
        sa.UniqueConstraint("id", name=op.f("uq_subreddits_id")),
    )
    with op.batch_alter_table("subreddits", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_subreddits_name"), ["name"], unique=True)

    op.create_table(
        "posts",
        sa.Column("reddit_id", sa.String(length=20), nullable=False),
        sa.Column("full_id", sa.String(length=24), nullable=False),
        sa.Column("subreddit_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("flair", sa.String(length=255), nullable=True),
        sa.Column("post_type", sa.String(length=32), nullable=True),
        sa.Column("domain", sa.String(length=255), nullable=True),
        sa.Column("permalink", sa.String(length=512), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=True),
        sa.Column("is_self", sa.Boolean(), nullable=True),
        sa.Column("author", sa.String(length=255), nullable=True),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("upvote_ratio", sa.Float(), nullable=True),
        sa.Column("num_comments", sa.Integer(), nullable=True),
        sa.Column("created_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "enriching",
                "enriched",
                "failed",
                name="poststatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("enriched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("fetch_error", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["subreddit_id"], ["subreddits.id"], name=op.f("fk_posts_subreddit_id_subreddits")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_posts")),
        sa.UniqueConstraint("id", name=op.f("uq_posts_id")),
    )
    with op.batch_alter_table("posts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_posts_created_utc"), ["created_utc"], unique=False)
        batch_op.create_index(batch_op.f("ix_posts_reddit_id"), ["reddit_id"], unique=True)
        batch_op.create_index(batch_op.f("ix_posts_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_posts_subreddit_id"), ["subreddit_id"], unique=False)
        batch_op.create_index(
            "ix_posts_subreddit_id_status", ["subreddit_id", "status"], unique=False
        )

    op.create_table(
        "comments",
        sa.Column("reddit_id", sa.String(length=20), nullable=False),
        sa.Column("post_id", sa.UUID(), nullable=False),
        sa.Column("parent_reddit_id", sa.String(length=24), nullable=True),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("author", sa.String(length=255), nullable=True),
        sa.Column("depth", sa.Integer(), nullable=False),
        sa.Column("is_submitter", sa.Boolean(), nullable=True),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("created_utc", sa.DateTime(timezone=True), nullable=True),
        sa.Column("permalink", sa.String(length=512), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["post_id"], ["posts.id"], name=op.f("fk_comments_post_id_posts"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_comments")),
        sa.UniqueConstraint("id", name=op.f("uq_comments_id")),
    )
    with op.batch_alter_table("comments", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_comments_post_id"), ["post_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_comments_reddit_id"), ["reddit_id"], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("comments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_comments_reddit_id"))
        batch_op.drop_index(batch_op.f("ix_comments_post_id"))

    op.drop_table("comments")
    with op.batch_alter_table("posts", schema=None) as batch_op:
        batch_op.drop_index("ix_posts_subreddit_id_status")
        batch_op.drop_index(batch_op.f("ix_posts_subreddit_id"))
        batch_op.drop_index(batch_op.f("ix_posts_status"))
        batch_op.drop_index(batch_op.f("ix_posts_reddit_id"))
        batch_op.drop_index(batch_op.f("ix_posts_created_utc"))

    op.drop_table("posts")
    with op.batch_alter_table("subreddits", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_subreddits_name"))

    op.drop_table("subreddits")
    # ### end Alembic commands ###
